#!/usr/bin/env python3
"""
FigForge - Scientific Figure Generator (Image Generation Only)

This is the image generation component of FigForge.
It receives a pre-generated MODULE LIST and creates publication-quality figures.

Usage as OpenClaw Skill:
    1. OpenClaw Agent analyzes text → generates MODULE LIST
    2. This skill receives MODULE LIST → generates figure
"""

import os
import sys
from pathlib import Path
from typing import Optional
import click
from dotenv import load_dotenv
from datetime import datetime

# Google Gemini imports (required for image generation)
try:
    from google import genai
    from google.genai import types
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False
    print("Warning: google-genai not installed. Image generation will not work.")


class FigForgeGenerator:
    """Image generation component - receives MODULE LIST, outputs figure"""
    
    def __init__(self, image_model: Optional[str] = None):
        """Initialize with image generation model only"""
        load_dotenv()
        
        # Initialize Gemini client for image generation
        if not GEMINI_AVAILABLE:
            raise ImportError(
                "google-genai package is required. "
                "Install with: pip install google-genai"
            )
        
        gemini_api_key = os.getenv("GEMINI_API_KEY")
        if not gemini_api_key:
            raise ValueError("GEMINI_API_KEY environment variable is required")
        
        self.gemini_client = genai.Client(api_key=gemini_api_key)
        
        # Image generation model (can be overridden)
        self.image_model = image_model or os.getenv("IMAGE_MODEL", "gemini-2.0-flash-exp-image-generation")
        
        # Output directory
        self.output_dir = Path(os.getenv("OUTPUT_DIR", "outputs"))
        self.output_dir.mkdir(exist_ok=True)
        
        # Load prompt template for figure generation
        self.prompts_dir = Path(__file__).parent / "prompts"
        self.step2_template = self._load_template("step2_figure_generation.txt")
    
    def _load_template(self, filename: str) -> str:
        """Load a prompt template"""
        template_path = self.prompts_dir / filename
        if not template_path.exists():
            raise FileNotFoundError(f"Prompt template not found: {template_path}")
        return template_path.read_text(encoding="utf-8")
    
    def generate_figure(self, module_list: str, output_path: Optional[Path] = None, 
                       input_filename: Optional[str] = None) -> Path:
        """
        Generate scientific figure from pre-generated MODULE LIST
        
        Args:
            module_list: The MODULE LIST (generated by OpenClaw's analysis model)
            output_path: Optional custom output path
            input_filename: Optional input filename for naming
            
        Returns:
            Path to the generated figure
        """
        print(f"Generating figure using {self.image_model}...")
        
        prompt = self.step2_template.format(module_list=module_list)
        
        try:
            # Create chat session with Gemini for image generation
            chat = self.gemini_client.chats.create(
                model=self.image_model,
                config=types.GenerateContentConfig(
                    response_modalities=['TEXT', 'IMAGE'],
                    temperature=0.7
                )
            )
            
            # Send message to generate image
            response = chat.send_message(prompt)
            
            # Process response parts
            image_saved = False
            if output_path is None:
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                if input_filename:
                    base_name = Path(input_filename).stem
                    output_path = self.output_dir / f"{base_name}_{timestamp}.png"
                else:
                    output_path = self.output_dir / f"scientific_figure_{timestamp}.png"
            
            for part in response.parts:
                if part.text is not None:
                    print(f"Model response: {part.text[:200]}...")
                elif image := part.as_image():
                    image.save(str(output_path))
                    print(f"Figure saved to: {output_path}")
                    image_saved = True
                    break
            
            if not image_saved:
                raise ValueError("No image was generated in the response")
            
            return output_path
            
        except Exception as e:
            print(f"Error generating figure: {e}")
            raise


@click.command()
@click.option(
    '--module-list', '-m',
    type=click.Path(exists=True, path_type=Path),
    required=True,
    help='Path to MODULE LIST file (generated by OpenClaw analysis)'
)
@click.option(
    '--output', '-o',
    type=click.Path(path_type=Path),
    help='Custom output path for the generated figure'
)
@click.option(
    '--image-model',
    type=str,
    default=None,
    help='Image generation model (default: gemini-2.0-flash-exp-image-generation)'
)
def main(module_list: Path, output: Optional[Path], image_model: Optional[str]):
    """
    FigForge - Generate scientific figures from MODULE LIST
    
    This tool receives a pre-generated MODULE LIST and creates publication-quality
    scientific figures. The MODULE LIST should be generated by OpenClaw's analysis
    model (Kimi/GLM/Qwen) from your scientific text.
    
    Example workflow:
        1. Use OpenClaw to analyze your text and generate MODULE LIST
        2. Run: python run.py -m module_list.txt -o figure.png
    
    Example:
        python run.py -m outputs/my_paper_module_list.txt -o my_figure.png
    """
    # Read MODULE LIST
    module_content = module_list.read_text(encoding="utf-8")
    print(f"Read MODULE LIST from: {module_list}")
    print(f"Content length: {len(module_content)} characters")
    
    # Initialize generator
    try:
        generator = FigForgeGenerator(image_model=image_model)
    except Exception as e:
        click.echo(f"Error initializing generator: {e}", err=True)
        sys.exit(1)
    
    # Generate figure
    try:
        figure_path = generator.generate_figure(
            module_content, 
            output, 
            str(module_list)
        )
        click.echo(f"\nFigure generated successfully!")
        click.echo(f"Output: {figure_path}")
    except Exception as e:
        click.echo(f"\nError generating figure: {e}", err=True)
        sys.exit(1)


if __name__ == "__main__":
    main()
